### ISSUE TITLE
pattern match expressions and statements with the same pattern

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#171]
`$X.pop(...)` doesn't match `x = l.pop(0)` or `print(l.pop(0)`

fixing this would make it simpler to match pattern anywhere in the AST

e.g. I have to have 12 patterns when I should only need 4 https://github.com/returntocorp/sgrep-rules/pull/72/commits/dcf2c5a3c7d79ce648ffc9b47fc8e60768b204ce#diff-ea429333db3631ca837612d41864864a

**Comment by ievans** [comment]
Correct, this is a general issue where statements and expressions are parsed and matched separately. 

You ought to be able to use `pattern-inside` to reduce the duplication, but sgrep doesn't enforce equality constraints on metavars across patterns at the moment: https://github.com/returntocorp/sgrep/issues/176

Since that's already filed, I'm going to simplify your issue to the expression vs statement problem.

**Comment by aryx** [comment]
This should work now drew.
Let me know if you can reduce your rule to just 4 patterns.
