### ISSUE TITLE
ellipsis across statements does not work for golang

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#188]
I believe there is already a (broken) test case for this here: https://github.com/returntocorp/sgrep/blob/develop/tests/go/dots_stmts.go

**Comment by aryx** [comment]
No, this test work.

**Comment by ievans** [comment]
Wrote another test case that does fail: https://github.com/returntocorp/sgrep/pull/193

**Comment by aryx** [comment]
This is because I need the trailing newlines for those.
The main problem is that Go supports implicit semicolons when it sees a newline. This is nice.
But if you are explicit,  foo() and foo();  are 2 different things for sgrep. One is an expression pattern,
the other a statement pattern (I know you would like to remove the difference at some point, but for now this is like that).
So if you just write foo(), I need to know if you want foo() the Expr or foo(); the Stmt and you do
that by adding or not the newline.

**Comment by aryx** [comment]
I can maybe try to infer what you want ...

**Comment by aryx** [comment]
It actually had nothing to do with the EOF and newlines ...
It was because during the transition from ast_go to ast_generic.ml I encapsulated the var decls inside a Block stmt, and was doing that only for Sequence sgrep patterns, which prevented the match.
