### ISSUE TITLE
Evaluate time needed to reimplement sgrep-lint

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/sgrep#382]
For binary compatibility and code readability, we might want to reimplement sgrep-lint.

This ticket would be done when we've created a broken-down time estimate for sgrep-lint reimplementation.

I can imagine two possible estimates:
1. Time to rewrite the existing Python code leveraging libraries (e.g. click), and refactoring for low cognitive complexity
2. Time to rewrite in an easily compilable language (e.g. golang), together with refactoring for low cognitive complexity

**Comment by brendongo** [comment]
Sgrep-lint can be broken down into the following parts:

- CLI Interface
- Downloading and Parsing Rule Files
- Running Sgrep-core
- Parsing Sgrep-core output
- Combining Boolean Logic of Rules and Sgrep-core output
- Output
- Misc/Glue

For refactoring in python [plus adding unit tests] here are my estimates for time
- CLI Interface (0.5 days) 
- Downloading and Parsing Rule Files (1 days)(tests: 0.5 days)
- Running Sgrep-core (0.5 days)(tests: 0.5 days)
- Parsing Sgrep-core output (0.5 days)(tests: 0.5 days)
- Combining Boolean Logic of Rules and Sgrep-core output (1 day)(tests: 1 day)
- Output (1 day)
- Misc/Glue (1 day)

Probably want to add a day for setting up automated QA/regression testing (1-2 days).

For switching to golang possibly add a day to each part to account for speed bumps in using a new language.

**Comment by aryx** [comment]
Honestly, if we want to switch to another language so that we can produce static binaries, I would seriously consider rewriting it in reason/ocaml. Anyway we need to ship the sgrep-core, and it would remove some parts and provide typed interface instead of untype JSON communication.
@ievans @DrewDennison. We would have just one binary instead of two that have to communicate with each other. If you have to use/learn a new language for this task, might be better to learn OCaml than Go.

**Comment by ievans** [comment]
@aryx OTOH, we might consider sgrep -> libsgrep and then use C extensions as the API; this could make it easier for others to build novel applications off of sgrep. Equalizing the playing field for all languages.

**Comment by brendongo** [comment]
I think there is a case to be made to just write it in ocaml so we dont need 2 languages to maintain sgrep.
