### ISSUE TITLE
match on type of immediate

### ISSUE THREAD

**Issue by ievans** [returntocorp/sgrep#49]
```
os.remove($X: int)
```

should match

```
os.remove(5)
```

`os.remove($X: float)` -> `os.remove(1.0)`
`os.remove($X: str)` -> `os.remove("1.0")`

Etc., for the python primitive types seen as immediates

**Comment by ievans** [comment]
@aryx I was unable to get this to work using the patterns in https://github.com/returntocorp/sgrep-rules/blob/develop/python/exceptions/exceptions.yaml#L7-L10; ie:

`raise $X: int` fails to parse, but `raise ($X: int)` did not trigger the appropriate line. Any ideas?

**Comment by aryx** [comment]
There are some ambiguities in the python grammar if you use $X : int anywhere in an expression, it's because K: V is also a key/value in a dictionary. Right now I've extended the python gramamr to allow X:T to appear only in arguments (the examples you had above). I can extend that to anywhere, but then you will have to use parenthesis around, as in foo(($X:int)). What do you prefer?

**Comment by ievans** [comment]
I think the approach you took is good! Thanks for the clarification
