### ISSUE TITLE
constant propagation for Python

### ISSUE THREAD

**Issue by minusworld** [returntocorp/sgrep#7]

**Comment by ievans** [comment]
@aryx do you have a good idea for demoing a python check that relies on dataflow?

**Comment by aryx** [comment]
As we talked, the example mentioned in the sgrep meetup future work slides:
boto3.client(aws_pass="...") should match code where the password was stored in a constant string before as in  pass="a7844"; boto3.client(aws_pass=pass).

We could propagate constant, or more generally normalize the AST so that one pattern match more variations.
another example is x = get(); y = x; eval(y); that we would like a pattern like $X = get();...; eval($X) match because y is really an alias for x.
This could be solved more generally though with tagging expression with tainting information (could even be an intraprocedural analysis).

**Comment by aryx** [comment]
Should work now.

**Comment by aryx** [comment]
I mean the easy cases are working
